
com:
  example:
    consentchannel:
      # Internal client sample, e.g. internet banking
      internalClientId: Le8cw0g8ZkPZnicEIbNZPy9DPUNXHQVM
      internalClientSecret: sLELKL71Lb5SR3LA
      oauthUri: http://poc-pa/oauth
      consentMgtUri: http://localhost:8080/consents
server:
  port: 8999

