
com:
  example:
    consentchannel:
      # Internal client sample, e.g. internet banking
      internalClientId: Le8cw0g8ZkPZnicEIbNZPy9DPUNXHQVM
      internalClientSecret: sLELKL71Lb5SR3LA
      oauthUri: https://ec2-34-246-195-42.eu-west-1.compute.amazonaws.com:3000/as
      consentMgtUri: http://localhost:8080/consents
      keystore:
server:
  port: 8090

spring:
  application:
    name: consentchannel


#  logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=
#  DEBUG
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
